export class GithubRepositoryEntity {
  constructor(
    public id?: number,
    public name?: string,
    public fullName?: string,
    public owner?: Owner,
    public htmlUrl?: string,
    public description?: string,
    public fork?: boolean,
    public url?: string,
    public forksUrl?: string,
    public keysUrl?: string,
    public collaboratorsUrl?: string,
    public teamsUrl?: string,
    public hooksUrl?: string,
    public issueEventsUrl?: string,
    public eventsUrl?: string,
    public assigneesUrl?: string,
    public branchesUrl?: string,
    public tagsUrl?: string,
    public blobsUrl?: string,
    public gitTagsUrl?: string,
    public gitRefsUrl?: string,
    public treesUrl?: string,
    public statusesUrl?: string,
    public languagesUrl?: string,
    public stargazersUrl?: string,
    public contributorsUrl?: string,
    public subscribersUrl?: string,
    public subscriptionUrl?: string,
    public commitsUrl?: string,
    public gitCommitsUrl?: string,
    public commentsUrl?: string,
    public issueCommentUrl?: string,
    public contentsUrl?: string,
    public compareUrl?: string,
    public mergesUrl?: string,
    public archiveUrl?: string,
    public downloadsUrl?: string,
    public issuesUrl?: string,
    public pullsUrl?: string,
    public milestonesUrl?: string,
    public notificationsUrl?: string,
    public labelsUrl?: string,
    public releasesUrl?: string,
    public deploymentsUrl?: string,
    public createdAt?: string,
    public updatedAt?: string,
    public pushedAt?: string,
    public gitUrl?: string,
    public sshUrl?: string,
    public cloneUrl?: string,
    public svnUrl?: string,
    public homepage?: string,
    public size?: number,
    public stargazersCount?: number,
    public watchersCount?: number,
    public language?: string,
    public hasIssues?: boolean,
    public hasProjects?: boolean,
    public hasDownloads?: boolean,
    public hasWiki?: boolean,
    public hasPages?: boolean,
    public hasDiscussions?: boolean,
    public forksCount?: number,
    public mirrorUrl?: string,
    public archived?: boolean,
    public disabled?: boolean,
    public openIssuesCount?: number,
    public license?: License,
    public allowForking?: boolean,
    public isTemplate?: boolean,
    public webCommitSignoffRequired?: boolean,
    public topics?: string[],
    public visibility?: string,
    public forks?: number,
    public openIssues?: number,
    public watchers?: number,
    public defaultBranch?: string
  ) {}
}

export class License {
  constructor(
    public key?: string,
    public name?: string,
    public spdxId?: string,
    public url?: string,
    public nodeId?: string
  ) {}
}

export class Owner {
  constructor(
    public login?: string,
    public id?: number,
    public nodeId?: string,
    public avatarUrl?: string,
    public gravatarId?: string,
    public url?: string,
    public htmlUrl?: string,
    public followersUrl?: string,
    public followingUrl?: string,
    public gistsUrl?: string,
    public starredUrl?: string,
    public subscriptionsUrl?: string,
    public organizationsUrl?: string,
    public reposUrl?: string,
    public eventsUrl?: string,
    public receivedEventsUrl?: string,
    public type?: string,
    public siteAdmin?: boolean
  ) {}
}
